site_name: Leylines-Docu
#cosmo|cyborg|readthedocs|yeti|journal|bootstrap|readable|united|simplex|flatly|spacelab|amelia|cerulean|slate|mkdocs
#theme: readthedocs
theme:
    name: 'material'
    logo: 'leylines-sign.png'
docs_dir: 'doc'
site_dir: '../docroot/home'
markdown_extensions:
  - markdown.extensions.admonition
strict: false
nav:
- Home: 'index.md'
- TerriaJS-Docu: '../guide/index.html'
- terriajs-Reference: '../leylinesjs/7.11.5/index.html'
- leylines-cli-Reference: '../leylines-cli/0.1.0/index.html'
- leylines-geodesy-Reference: '../leylines-geodesy/0.1.0/index.html'
